### ISSUE TITLE
zerotier  请求更新到1.6.2版本

### ISSUE THREAD

**Issue by lifetyper** [coolsnowwolf/packages#105]
官方release版本前几天发布了1.6.2版本，openwrt版本昨天也更新到了这个版本，希望这边可以同步一下。

谢谢！

参考：
https://github.com/mwarning/zerotier-openwrt/commit/6dae2e570369e1258a327d2165893d02f7a50ab7

**Comment by Beginner-Go** [comment]
自己提交啊 话说这个东西有什么用
