### ISSUE TITLE
zerotier 请求更新到 1.6.3 版本

### ISSUE THREAD

**Issue by CallMeR** [coolsnowwolf/packages#124]
官方release版本前几天发布了 1.6.3 版本，openwrt 版本也更新到了这个版本，希望这边可以同步一下。

谢谢！

参考：

https://github.com/mwarning/zerotier-openwrt/commit/b7143db129f5d28530dbb9ed0d9a5566ed75a171

**Comment by Saxon-Sun** [comment]
已提交pr [https://github.com/coolsnowwolf/packages/pull/125](https://github.com/coolsnowwolf/packages/pull/125)
