### ISSUE TITLE
python3-libsemanage下载链接错误

### ISSUE THREAD

**Issue by ITdesk01** [coolsnowwolf/packages#163]
请更新这里makefile下载链接
packages/lang/python/python3-libsemanage/Makefile

错误链接
https://github.com/SELinuxProject/selinux/releases/download/20200710

正确链接
https://github.com/SELinuxProject/selinux/releases/download/3.2

**Comment by coolsnowwolf** [comment]
可以提交个 pr 修复

**Comment by ITdesk01** [comment]
> 可以提交个 pr 修复

已经创建了
