### ISSUE TITLE
更新smartdns

### ISSUE THREAD

**Issue by moruiris** [coolsnowwolf/packages#215]
L大能不能更新下smartdns源码版本

**Comment by EnnawYang** [comment]
巴不得扬了，还更新

**Comment by breakings** [comment]
# smartdns
sed -i 's/PKG_VERSION:=.*/PKG_VERSION:=1.2021.34/' feeds/packages/net/smartdns/Makefile
sed -i 's/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=756029f5e9879075c042030bd3aa3db06d700270/' feeds/packages/net/smartdns/Makefile
sed -i 's/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=c2979d956127946861977781beb3323ad9a614ae55014bc99ad39beb7a27d481/' feeds/packages/net/smartdns/Makefile
