### ISSUE TITLE
zerotier 1.8.6在 lede源码编译的acrh17固件中无法启动

### ISSUE THREAD

**Issue by JayXus** [coolsnowwolf/packages#385]
SSH 登录后，执行 zerotier-cli 
提示  Segmentation fault

ACRH17固件，源码  https://github.com/coolsnowwolf/lede

 请大佬看下什么问题，感谢

**Comment by zjy2200656** [comment]
同处理器竞斗云表示同样无法启动

**Comment by JayXus** [comment]
回退到1.8.4版本，可以正常使用
