### ISSUE TITLE
更新后好像缺少依赖

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/packages#576]
Create index file './feeds/packages.index'
Create index file './feeds/luci.index'
Create index file './feeds/routing.index'
Create index file './feeds/telephony.index'
Create index file './feeds/oui.index'
Create index file './feeds/helloworld.index'
WARNING: Makefile 'package/feeds/packages/python-paho-mqtt/Makefile' has a dependency on 'python3-uuid', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed oui.
Installing all packages from feed helloworld.

更新后好像缺依赖

**Comment by 1582130940** [comment]
把https://github.com/coolsnowwolf/packages/commit/a54b8ebf60d1dd0dc18f94d84c4429b9a6942b87 revert掉
