### ISSUE TITLE
更新源码后缺依赖

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/packages#581]
WARNING: Makefile 'package/feeds/packages/libesmtp/Makefile' has a build dependency on 'meson/host', which does not exist
WARNING: Makefile 'package/feeds/packages/midisport-firmware/Makefile' has a dependency on 'fxload', which does not exist
WARNING: Makefile 'package/feeds/packages/openvswitch/Makefile' has a build dependency on 'python-six/host', which does not exist
WARNING: Makefile 'package/feeds/packages/ovn/Makefile' has a build dependency on 'python-six/host', which does not exist

**Comment by Beginner-Go** [comment]
@1582130940 can you look？

**Comment by 1582130940** [comment]
> @1582130940 can you look？
https://github.com/coolsnowwolf/packages/pull/583
https://github.com/coolsnowwolf/packages/pull/585
https://github.com/coolsnowwolf/lede/pull/10396
我提交了已经，阿巴阿巴
