### ISSUE TITLE
关于python-six/host的警告

### ISSUE THREAD

**Issue by ecrasy** [coolsnowwolf/packages#588]
最近一直弹这个烦人的警告：
WARNING: Makefile 'package/feeds/packages/openvswitch/Makefile' has a build dependency on 'python-six/host', which does not exist

我看了feeds/packages/lang/python/python-six/Makefile，
好像只定义了python-six ？
没有定义python-six/host ？

能不能修复一下这个warning？
要不把不存在的依赖去掉？
要不把需要的依赖加上去？
一直弹很烦啊。

**Comment by 1582130940** [comment]
https://github.com/coolsnowwolf/packages/pull/590
