### ISSUE TITLE
 ERROR: package/feeds/packages/iperf3 failed to build (build variant: nossl).

### ISSUE THREAD

**Issue by zgc** [coolsnowwolf/packages#620]
ifeq (nossl,ssl)
bash: -c: line 1: syntax error near unexpected token `nossl,ssl'
bash: -c: line 1: `ifeq (nossl,ssl)'
make[3]: *** [Makefile:113: /home/lede/coding/Actions-LEDE/openwrt/bin/packages/x86_64/packages/libiperf3_3.12-1_x86_64.ipk] Error 2
make[3]: Leaving directory '/home/lede/coding/Actions-LEDE/openwrt/feeds/packages/net/iperf3'
time: package/feeds/packages/iperf3/nossl/compile#0.16#0.01#0.16
    ERROR: package/feeds/packages/iperf3 failed to build (build variant: nossl).
make[2]: *** [package/Makefile:116: package/feeds/packages/iperf3/compile] Error 1
make[2]: Leaving directory '/home/lede/coding/Actions-LEDE/openwrt'
make[1]: *** [package/Makefile:110: /home/lede/coding/Actions-LEDE/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lede/coding/Actions-LEDE/openwrt'
make: *** [/home/lede/coding/Actions-LEDE/openwrt/include/toplevel.mk:231: world] Error 2

**Comment by alfredfenglq** [comment]
diy-part2.sh加上sed -i 's/,ssl/ ,ssl/' feeds/packages/net/iperf3/Makefile
