### ISSUE TITLE
msd_lite编译能通过，但是程序无法启动

### ISSUE THREAD

**Issue by moonerick** [coolsnowwolf/packages#665]
Please make sure that the issue subject starts with `<msd_lite>: `

This repo here is only for packages maintained in this repo.  For base packages residing in the same repo as the build system and maintained by core devs, please consider opening tickets there for more timely responses

Description:
msd_lite编译能通过，但是程序无法启动
```
Formating code blocks by wrapping them with pairs of ```
```
使用此包能完成编译，但程序无法启动，我将编译内容修改为这个资源里面的后可以正常启动
https://github.com/syb999/openwrt-19.07.1/tree/master/package/network/services/msd_lite

另外这里这个包里面的这个地方结尾多了一个a
URL:=https://github.com/rozhuk-im/msd_litea

**Comment by luxiaok** [comment]
![image](https://github.com/coolsnowwolf/packages/assets/3795104/2f0633ba-b2e9-4fd0-a2c4-b6864d06c59c)

这可以 close 了

**Comment by moonerick** [comment]
> ![image](https://private-user-images.githubusercontent.com/3795104/321681463-2f0633ba-b2e9-4fd0-a2c4-b6864d06c59c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODAxMzYsIm5iZiI6MTcxMjg3OTgzNiwicGF0aCI6Ii8zNzk1MTA0LzMyMTY4MTQ2My0yZjA2MzNiYS1iMmU5LTRmZDAtYTJjNC1iNjg2NGQwNmM1OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMjM1NzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2IzNTY1MzQyNTI1MWNkYjliYWZjZTRkNThkZDkwMjAxMmRmMTA5MDQ5OGM0ODhjZWQ4YzdmYjhmZWRiYmE1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WKhnd_0m1XN7o-rXLboXlq1H3CFmrLOO8ZlUq3vhOlM)
> 
> 这可以 close 了

<img width="653" alt="屏幕截图 2024-04-12 075753" src="https://github.com/coolsnowwolf/packages/assets/51778524/1f7347af-918f-402f-ae12-932b2613e492">
能添加这个功能么，我有现成的代码给你参考
