### ISSUE TITLE
Github Action编译x86固件smartdns报错

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/packages#688]
![image](https://github.com/coolsnowwolf/packages/assets/110249561/26ac6e21-37a9-430f-96dc-db93e6d4ab55)
@picmax

**Comment by picmax** [comment]
I don't have this issue. Please try to pull the official copy from https://github.com/pymumu/openwrt-smartdns/blob/master/Makefile to see if works.

**Comment by bi4tms** [comment]
> I don't have this issue. Please try to pull the official copy from https://github.com/pymumu/openwrt-smartdns/blob/master/Makefile to see if works.

After directly overwrite the file 'Makefile' in package/net/smartdns by the same file from your repository 'package/net/smartdns', someone else can build smartdns successfully. So the problem may come frome the format when codes are copyed and pasted.

**Comment by picmax** [comment]
It is possible but I don't have any problem with either file. Perhaps some build environments are more sensitive/picky than others. I will try to resubmit a pull request.

**Comment by bi4tms** [comment]
> It is possible but I don't have any problem with either file. Perhaps some build environments are more sensitive/picky than others. I will try to resubmit a pull request.

Thank you for the resubmition.

**Comment by picmax** [comment]
Actually, I downloaded the Makefile from both pymumu and lede repositories and compared them. The files are exactly the same. Not sure what caused your problem.

**Comment by bi4tms** [comment]
> Actually, I downloaded the Makefile from both pymumu and lede repositories and compared them. The files are exactly the same. Not sure what caused your problem.

I just downloaded the file 'Makefile' from lean's repository and yours and compared two files. SHA1 and MD5 of the two files were different.

**Comment by picmax** [comment]
You were right. Tabs were changed into spaces, causing the problem. New pull request submitted.
