### ISSUE TITLE
Can anyone help to update zerotier to 1.12.1?

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/packages#697]
there is a new version of ZT 1.12.1 and RN said there are significant performance improvement, can any one help to upgrade here? I tried directly change make file with updating version# and SHA256, and compile faild, seems need a build patch...

**Comment by MilesPoupart** [comment]
maybe refer to https://github.com/mwarning/zerotier-openwrt

**Comment by GreatMichaelLee** [comment]
> maybe refer to https://github.com/mwarning/zerotier-openwrt

谢谢，我把你这个下面的patch目录覆盖过来，然后Makefile里DEPENDS 加一个 +libatomic后，在lede上编译过了。建议哪位大佬pull request一下。

**Comment by avsba001** [comment]
> > maybe refer to https://github.com/mwarning/zerotier-openwrt
> 
> 谢谢，我把你这个下面的patch目录覆盖过来，然后Makefile里更新版本号/sha256，以及在DEPENDS 加一个 +libatomic后，在lede上编译过了。建议哪位大佬pull request一下。

我直接用官方packages替换lede 编译过的1.12.1
