### ISSUE TITLE
rust 1.75.0及以上版本会失去MIPS的支持，导致k2p等一众7621设备无法编译rust的工具

### ISSUE THREAD

**Issue by qwerttvv** [coolsnowwolf/packages#770]
https://github.com/rust-lang/rust/pull/115238/

最后一个支持MIPS的版本是[1.74.1](https://github.com/rust-lang/rust/releases/tag/1.74.1)

我觉得除非以后哪个工具要求最低rust版本1.75.0，不然的话是不是现在先降到1.74.1以支持数量庞大的这些设备会好一些啊

@MilesPoupart @HHJLKK @coolsnowwolf @Beginner-Go

**Comment by Beginner-Go** [comment]
放过mips吧 买个好点的arm
