### ISSUE TITLE
新版docker网络选项出现报错页面

### ISSUE THREAD

**Issue by Pacio** [coolsnowwolf/packages#778]
设备：x86
![image](https://github.com/coolsnowwolf/packages/assets/6836705/10cc698b-33a6-4f90-bd39-f79b3f735848)

![image](https://github.com/coolsnowwolf/packages/assets/6836705/62f7962e-298b-46cd-9af9-956c55ac34a2)

**Comment by Pacio** [comment]
容器可以正常运行，就是网络页面报错

**Comment by MilesPoupart** [comment]
网络页面确实有这个问题 但是感觉可能是对应luci app的问题？

**Comment by Pacio** [comment]
> 网络页面确实有这个问题 但是感觉可能是对应luci app的问题？

最新源码问题不少，除了这个docker还有就是网络间歇性中断，补丁打出Bug了
