### ISSUE TITLE
有大佬更新一下`netdata`吗

### ISSUE THREAD

**Issue by devioa** [coolsnowwolf/packages#830]
最新版 netdata 和现在仓库里的 1.33.1 版本相比大改，界面布局更友好，数据展示也更合理丰富了
我自己试了下拉最新版源码编译一直报错就没折腾了，才疏学浅😭
但新版本这个是真的好看啊🤤
![1](https://github.com/coolsnowwolf/packages/assets/38558065/d9ed068a-17f3-40ee-84c1-6d1ec85a2268)

**Comment by wlshdjj** [comment]
新版ui它卡得一b，i9十二代运行都卡

**Comment by wlshdjj** [comment]
新版ui它卡得一b，i9十二代运行都卡

**Comment by devioa** [comment]
> 新版ui它卡得一b，i9十二代运行都卡

你浏览器没有硬件加速？
